# Generated by Django 4.1.7 on 2023-02-17 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TabelaCSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_vigencia', models.CharField(max_length=4, verbose_name='Ano de Vigência')),
            ],
            options={
                'verbose_name': 'Tabela de contribuição à seguridade social',
                'verbose_name_plural': 'Tabelas de contribuição à seguridade social',
            },
        ),
        migrations.CreateModel(
            name='TabelaIRPF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_vigencia', models.CharField(max_length=4, verbose_name='Ano de Vigência')),
                ('deducao_dependente_mes', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Desconto mensal por dependente')),
            ],
            options={
                'verbose_name': 'Tabela do imposto de renda',
                'verbose_name_plural': 'Tabelas do imposto de renda',
            },
        ),
        migrations.CreateModel(
            name='AliquotaIRPF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aliquota', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Alíquota')),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Inicial')),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Final')),
                ('tabela_irpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.tabelairpf', verbose_name='Tabela IRPF')),
            ],
            options={
                'verbose_name': 'Alíquota do imposto de renda',
                'verbose_name_plural': 'Alíquotas do imposto de renda',
            },
        ),
        migrations.CreateModel(
            name='AliquotaCSS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aliquota', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Alíquota')),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Inicial')),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Final')),
                ('tabela_css', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.tabelacss', verbose_name='Tabela CSS')),
            ],
            options={
                'verbose_name': 'Alíquota de contribuição à seguridade social',
                'verbose_name_plural': 'Alíquotas de contribuição à seguridade social',
            },
        ),
    ]
